name: CI/CD for Flask App on Render

# L'action est déclenchée lorsque du code est poussé sur la branche master
on:
  push:
    branches:
      - master

jobs:
  deploy:
    # Déployer sur un environnement Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code depuis GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Installer les dépendances de l'application
      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      # Étape 3 : Déployer l'application sur Render
      - name: Deploy to Render
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            --data '{"serviceId": "${{ secrets.RENDER_SERVICE_ID }}"}' \
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys
